name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest   # nên dùng Ubuntu thay vì Windows

    steps:
      # Checkout code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'   # bạn chỉnh theo version đang dùng
          channel: 'stable'

      # Build Flutter project
      - name: Build
        run: |
          flutter pub get
          flutter build apk --debug

      # SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
